export const courseList = [
    {
        courseId: 0,
        courseName: "MTC導覽",
        courseType: "高端",
        duration: "30",
        durationType: "min",
        capacity: "30",
        speaker: "MTC Team",
        Status: 2,
        Customize: false,
        order: 1,
    },
    {
        courseId: 1,
        courseName: "開場 Opening",
        courseType: "高端",
        duration: "15",
        durationType: "min",
        capacity: "30",
        speaker: "MTC Team",
        Status: 1,
        Customize: false,
        order: 1,
    },
    {
        courseId: 2,
        courseName: "微軟的轉型之旅：從桌面到雲端的革命",
        courseType: "高端",
        duration: "30",
        durationType: "min",
        capacity: "30",
        speaker: "Peter Hu",
        Status: 1,
        Customize: false,
        order: 1,
    },
    {
        courseId: 3,
        courseName: "從 Edge 到全球數據中心佈署：微軟的雲端戰略",
        courseType: "高端",
        duration: "30",
        durationType: "min",
        capacity: "10",
        speaker: "Peter Hu",
        Status: 1,
        Customize: false,
        order: 1,
    },
    {
        courseId: 4,
        courseName: "微軟的 5G+IoT 技術戰略與智慧製造",
        courseType: "高端",
        duration: "30",
        durationType: "min",
        capacity: "10",
        speaker: "Peter Hu",
        Status: 1,
        Customize: false,
        order: 1,
    },
    {
        courseId: 5,
        courseName: "企業財務數位化轉型的旅程與實戰心法",
        courseType: "高端",
        duration: "30",
        durationType: "min",
        capacity: "10",
        speaker: "Hannah Wang",
        Status: 1,
        Customize: false,
        order: 1,
    },
    {
        courseId: 6,
        courseName: "企業人資數位化轉型的旅程與實戰心法",
        courseType: "高端",
        duration: "30",
        durationType: "min",
        capacity: "10",
        speaker: "Linda Wang",
        Status: 1,
        Customize: false,
        order: 1,
    },
    {
        courseId: 7,
        courseName: "金融業數位轉型的旅程與實戰心法",
        courseType: "高端",
        duration: "30",
        durationType: "min",
        capacity: "10",
        speaker: "Jimmy Liu",
        Status: 1,
        Customize: false,
        order: 1,
    },
    {
        courseId: 8,
        courseName: "雲端時代的資訊安全架構指南",
        courseType: "技術",
        duration: "30",
        durationType: "min",
        capacity: "10",
        speaker: "White Pai",
        Status: 1,
        Customize: false,
        order: 1,
    },
    {
        courseId: 9,
        courseName: "微軟的人工智慧發展藍圖",
        courseType: "技術",
        duration: "30",
        durationType: "min",
        capacity: "10",
        speaker: "Ethan Huang",
        Status: 1,
        Customize: false,
        order: 1,
    },
    {
        courseId: 10,
        courseName: "雲端時代的資訊安全最佳做法",
        courseType: "技術",
        duration: "30",
        durationType: "min",
        capacity: "10",
        speaker: "Jason Lin",
        Status: 1,
        Customize: false,
        order: 1,
    },
    {
        courseId: 11,
        courseName: "在雲端運行 SAP：來自微軟的最佳實踐",
        courseType: "技術",
        duration: "30",
        durationType: "min",
        capacity: "10",
        speaker: "James Wu",
        Status: 1,
        Customize: false,
        order: 1,
    },
    {
        courseId: 12,
        courseName: "開發流程現代化與雲原生應用程式的最佳實踐",
        courseType: "技術",
        duration: "30",
        durationType: "min",
        capacity: "10",
        speaker: "Huier Huang",
        Status: 1,
        Customize: false,
        order: 1,
    },
    {
        courseId: 13,
        courseName:
            "從彙整資料資產到改善營運的洞見: 微軟雲端資料服務的策略與藍圖",
        courseType: "技術",
        duration: "30",
        durationType: "min",
        capacity: "10",
        speaker: "Ethan Huang",
        Status: 1,
        Customize: false,
        order: 1,
    },
    {
        courseId: 14,
        courseName: "微軟 Azure 雲平台基礎建設發展藍圖及技術概覽",
        courseType: "技術",
        duration: "30",
        durationType: "min",
        capacity: "10",
        speaker: "Ken Hung",
        Status: 1,
        Customize: false,
        order: 1,
    },
    {
        courseId: 15,
        courseName: "微軟 IoT 平台發展藍圖與最佳做法指南",
        courseType: "技術",
        duration: "30",
        durationType: "min",
        capacity: "10",
        speaker: "Joe Lin",
        Status: 1,
        Customize: false,
        order: 1,
    },
];
